"""
Pydantic models for Sales Representative Registry.

Provides data models for:
- Sales representatives (registration, status, calendar)
- Test prospects (assignment, tracking)
- Conversation states for bot flow
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field


class SalesRepStatus(str, Enum):
    """Status of a sales representative."""
    PENDING = "pending"      # Registered, awaiting approval (not used in auto-approve)
    ACTIVE = "active"        # Approved and active
    SUSPENDED = "suspended"  # Temporarily disabled
    REMOVED = "removed"      # Permanently removed


class ProspectStatus(str, Enum):
    """Status of a test prospect."""
    UNREACHED = "unreached"           # Not yet contacted
    CONTACTED = "contacted"           # Initial contact made
    IN_CONVERSATION = "in_conversation"  # Actively chatting
    CONVERTED = "converted"           # Became a client
    ARCHIVED = "archived"             # No longer active


class ConversationState(str, Enum):
    """States for the registration bot conversation flow."""
    IDLE = "idle"                        # No active conversation
    ASK_REGISTER = "ask_register"        # Asked if user wants to register
    ASK_NAME = "ask_name"                # Waiting for name
    ASK_EMAIL = "ask_email"              # Waiting for email
    REGISTERED = "registered"            # Registration complete
    ASK_UNREGISTER = "ask_unregister"    # Confirming unregistration


class SalesRepresentative(BaseModel):
    """A registered sales representative."""
    id: Optional[str] = None  # UUID, generated by database
    telegram_id: int
    telegram_username: Optional[str] = None
    name: str
    email: str
    status: SalesRepStatus = SalesRepStatus.ACTIVE
    calendar_account_name: Optional[str] = None
    is_admin: bool = False
    registered_at: Optional[datetime] = None
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None  # UUID of admin
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        use_enum_values = True


class TestProspect(BaseModel):
    """A test prospect for sales rep training."""
    id: str  # String ID like "test_001"
    telegram_id: str  # @username
    name: str
    context: Optional[str] = None
    status: ProspectStatus = ProspectStatus.UNREACHED
    assigned_rep_id: Optional[str] = None  # UUID of assigned rep
    email: Optional[str] = None
    notes: Optional[str] = None
    last_contact_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    class Config:
        use_enum_values = True


class UserSession(BaseModel):
    """Tracks the current conversation state for a user."""
    telegram_id: int
    state: ConversationState = ConversationState.IDLE
    temp_name: Optional[str] = None
    temp_email: Optional[str] = None
    last_activity: datetime = Field(default_factory=datetime.now)

    class Config:
        use_enum_values = True
